Hw 1 classify double
ArtemTsukanov/made-cpp-2020-hw pull request #1
Opened 2020-09-16 23:59 UTC by ArtemTsukanov

2020-09-18 14:47 UTC, xterrafunny requested changes

2020-09-18 14:47 UTC, xterrafunny commented on classify double/solution.c
> +        }
Можно переписать на одну битовую операцию

2020-09-18 14:47 UTC, xterrafunny commented on classify double/solution.c
> +        }
Можно переписать на одну битовую операцию

2020-09-18 14:47 UTC, xterrafunny commented on classify double/solution.c
> +    }
Можно переписать на одну битовую операцию

2020-09-18 14:47 UTC, xterrafunny commented on classify double/solution.c
> +    }
Можно переписать на одну битовую операцию

2020-09-18 14:47 UTC, xterrafunny commented on classify double/solution.c
> +    }
Можно переписать на одну битовую операцию

2020-09-18 14:47 UTC, xterrafunny commented on classify double/solution.c
> +    }
Можно переписать на одну битовую операцию

2020-09-18 14:47 UTC, xterrafunny commented on classify double/solution.c
> +    }
Можно переписать на одну битовую операцию

2020-09-18 18:37 UTC, ArtemTsukanov commented
Как сделать за одну битовую – не понятно. Придумал за две, выделяя части дабла.

2020-09-20 11:31 UTC, ArtemTsukanov commented
Переписал на одну битовую операцию для простоты проверки. По производительности разницы нет. Не выносил константы по той же причине.

2020-09-20 11:45 UTC, ArtemTsukanov commented
Смотреть последний :)

2020-09-20 12:59 UTC, merged